# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homekit: !include configuration/homekit.yaml
template: !include configuration/template.yaml
timer: !include configuration/timer.yaml
input_boolean: !include configuration/input_boolean.yaml
input_number: !include configuration/input_number.yaml
input_datetime: !include configuration/input_datetime.yaml
input_button: !include configuration/input_button.yaml

light groups: !include configuration/light_groups.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.0.0/16
# timer:
#   contact_sensor_debounce:
#     name: Contact Sensor Debounce
#     duration: "00:00:05"
# input_boolean:
#   contact_sensor_latch:
#     name: Contact Sensor Latch
#     initial: off
