- platform: template
  switches:
    heater_automation_switch:
      friendly_name: Heater Automation
      value_template: "{{ is_state('input_boolean.heater_automation_enable', 'on') }}"
      turn_on:
        service: input_boolean.turn_on
        data:
          entity_id: input_boolean.heater_automation_enable
      turn_off:
        service: input_boolean.turn_off
        data:
          entity_id: input_boolean.heater_automation_enable
      icon_template: >-
        {% if is_state('input_boolean.heater_automation_enable', 'on') %}
          mdi:radiator
        {% else %}
          mdi:radiator-off
        {% endif %}
    christmas_tree_automation_switch:
      friendly_name: Christmas Tree Automation
      value_template: "{{ is_state('input_boolean.christmas_tree_automation_enable', 'on') }}"
      turn_on:
        service: input_boolean.turn_on
        data:
          entity_id: input_boolean.christmas_tree_automation_enable
      turn_off:
        service: input_boolean.turn_off
        data:
          entity_id: input_boolean.christmas_tree_automation_enable
      icon_template: >-
        {% if is_state('input_boolean.christmas_tree_automation_enable', 'on') %}
          mdi:tree
        {% else %}
          mdi:tree-outline
        {% endif %}
